using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CycleProvider.Contracts
{
    /// <summary>
    /// Contract for base definition of person
    /// </summary>
    public interface IPerson
    {
        /// <summary>
        /// Autogenerated number incremented by 1
        /// </summary>
        int Id { get; }
        /// <summary>
        /// First name of person
        /// </summary>
        /// <exception cref="HrException">First Name must be single word alphanumerical only</exception>
        string FirstName { get; set; }
        string LastName { get; set; }
        DateTime BirthDate { get; set; }
    }
}
